version: '3.7'
services:
  DatabaseService:
    container_name: DatabaseService
    image: mcr.microsoft.com/mssql/server:2019-latest
    environment:
      SA_PASSWORD: ${DB_ROOT_PASSWORD}
      ACCEPT_EULA: Y
    volumes:
      - mssqldata:/var/opt/mssql
      - ./database_service/script:/docker-entrypoint-initdb.d
    ports:
      - '1433:1433'
    restart: unless-stopped
    networks:
      - backend

  OrderServiceAPI:
   # container_name: OrderServiceAPI
    build:
      context: ./customer_service
      dockerfile: Dockerfile
    image: customer_service_api:1
    environment:
      DB_HOST: DatabaseService
      DB_PASS: ${DB_ROOT_PASSWORD}
      DB_NAME: ${DB_NAME}
      DB_USER: ${DB_USER}
      SPRING_PROFILES_ACTIVE: development
    env_file:
      - .env
    ports:
      - "8080:8080"
    restart: always
    depends_on:
      - DatabaseService
    networks:
      - backend
    
  MailService:
    build:
      context: ./Production/PyMail/PyMail
      dockerfile: Dockerfile
    command: python3 main.py
    depends_on: broker
    ports:
      - "5000:5000"

volumes:
  mssqldata:

networks:
  backend:
    name: backend
